"""
Day 14 retrospective — runs on/near 2026-05-29, the operator's return cap.

Writes a comprehensive "Day 14 Retrospective" block at the top of STATE.md
covering everything cumulative since Day 0 (2026-05-16). Idempotent — if a
retrospective block already exists, it's replaced rather than duplicated.

Designed to be triggered by:
  - schedule (cron): May 29 at 16:00 UTC each year
  - workflow_dispatch: any time

No env vars required — pure repo introspection.
"""
from __future__ import annotations
import csv
import datetime as dt
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATE = ROOT / "STATE.md"
OUTBOUND = ROOT / "outbound"
QUEUE = ROOT / "intake-queue"
RUNS = ROOT / "runs"

DAY_ZERO = dt.datetime(2026, 5, 16)  # the autonomous-mode start
HEADER_RE = re.compile(r"^## 2026-05-\d{2} — DAY 14 RETROSPECTIVE.*$", re.M)


def _csv_rows(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open() as f:
        return list(csv.DictReader(f))


def _count_files(folder: Path, pattern: str) -> int:
    return sum(1 for _ in folder.glob(pattern) if _.is_file()) if folder.exists() else 0


def build_block() -> str:
    now = dt.datetime.now(dt.timezone.utc).replace(tzinfo=None)
    days = max(0, (now - DAY_ZERO).days)

    sent = _csv_rows(OUTBOUND / "sent.csv")
    sent_ok = [r for r in sent if str(r.get("ok", "")).lower() in ("true", "1")]

    signups = _csv_rows(OUTBOUND / "signups.csv")
    signups_ok = [r for r in signups if str(r.get("onboarding_sent", "")).lower() in ("true", "1")]

    intakes = _csv_rows(OUTBOUND / "intakes.csv")
    replies = _csv_rows(OUTBOUND / "cold_replies.csv")
    needs_human = _csv_rows(OUTBOUND / "needs_human.csv")
    suppressions = _csv_rows(OUTBOUND / "suppressions.csv")

    processed = _count_files(QUEUE / "_processed", "*.result.json")
    failed = _count_files(QUEUE / "_failed", "*.error.txt")
    pending = _count_files(QUEUE, "*.json")

    triage_runs = _count_files(RUNS, "triage-*.json") if RUNS.exists() else 0

    # Reply rate (rough, since we don't track reply-attribution to specific sends here)
    reply_rate = (len(replies) / len(sent) * 100) if sent else 0.0

    lines = [
        f"## {now.strftime('%Y-%m-%d')} — DAY 14 RETROSPECTIVE",
        "",
        f"_Auto-generated by `day-14-retrospective.yml` at {now.strftime('%H:%M UTC')}_",
        f"_Cumulative since Day 0 ({DAY_ZERO.strftime('%Y-%m-%d')}) — **{days} days**._",
        "",
        "### Headline numbers",
        f"- Cold emails sent: **{len(sent)}** (delivered ok: {len(sent_ok)})",
        f"- Pilot signups received: **{len(signups)}** (onboarded ok: {len(signups_ok)})",
        f"- Cold replies received: **{len(replies)}** (rough reply rate: {reply_rate:.1f}% of sent)",
        f"- Intakes processed: **{processed}** · failed: **{failed}** · pending: **{pending}**",
        f"- Suppression list size: **{len(suppressions)}**",
        f"- Triage workflow runs: **{triage_runs}**",
        f"- Items in `outbound/needs_human.csv`: **{len(needs_human)}**",
        "",
        "### What the operator should read first (in order)",
        "1. This block (you're here).",
        "2. `outbound/needs_human.csv` — anything queued for human attention.",
        "3. `intake-queue/_failed/` — anything the quote engine couldn't process.",
        "4. The Actions log for any red runs in the past 14 days: https://github.com/finleystephenson/crewOS/actions",
        "5. The full STATE.md history below this block.",
        "",
        "### Decisions to make",
        "Based on the numbers above and the qualitative reads in `outbound/cold_replies.csv` + the Reddit thread:",
        "- **Keep going** — autopilot is producing pilot signups and processing intakes. Refill `targets.csv`, fix any red workflows, write a Day 15 follow-up post on Reddit.",
        "- **Pivot** — the wedge isn't landing. Check `outbound/cold_replies.csv` sentiment, talk to the people who replied, and consider one of the runners-up from `research/decision.md` (BidLift or CareCompliance).",
        "- **Pause** — nothing landed worth continuing. Disable the cron triggers (Settings → Actions → disable each workflow) and let the domain auto-renew for a future restart.",
        "",
        "### Known issues that survived the 14 days (if any)",
        "_If any of these are now resolved, mark them ✅ when you read this._",
        "- 🟡 ImprovMX DNS conflict (rogue `MX @ inbound-smtp.eu-west-1.amazonaws.com` at Hostinger). Estimated ~50% inbound loss across the 14 days. One Hostinger click fixes.",
        "- 🟡 `outbound/targets.csv` may still be empty — cold-email channel is silent without targets.",
        "- 🟡 No file uploads in v0 intake (Formspree free tier limitation).",
        "",
        "### Workflow health (last 14 days)",
        "Look at the green/red ratio: https://github.com/finleystephenson/crewOS/actions",
        "",
    ]
    return "\n".join(lines)


def write_state() -> dict:
    block = build_block()
    text = STATE.read_text() if STATE.exists() else "# STATE\n\n_Updated end-of-session. Most recent at top._\n\n"

    if HEADER_RE.search(text):
        # Replace existing retrospective block (everything from the heading
        # to the next `## ` heading or EOF).
        text = re.sub(
            r"## 2026-05-\d{2} — DAY 14 RETROSPECTIVE.*?(?=\n## |\Z)",
            block,
            text,
            count=1,
            flags=re.S,
        )
    else:
        marker = "_Updated end-of-session. Most recent at top._"
        if marker in text:
            head, _, tail = text.partition(marker)
            text = head + marker + "\n\n" + block + "\n" + tail.lstrip("\n")
        else:
            text = text.rstrip() + "\n\n" + block + "\n"
    STATE.write_text(text)
    return {"written": True, "bytes": len(block)}


def _main() -> int:
    print(json.dumps(write_state(), indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
