"""
Weekly status — every Friday afternoon UK, write a "Week N" summary entry
into STATE.md.

What it tallies (from the repo state, not external APIs):
- Cold emails sent (count rows in outbound/sent.csv with sent_at this week)
- Pilot signups received (count rows in outbound/signups.csv with ts this week)
- Intakes processed successfully (intake-queue/_processed/*.json this week)
- Intakes failed (intake-queue/_failed/*.json this week)
- Cold replies received (outbound/cold_replies.csv this week)
- Anything in outbound/needs_human.csv that hasn't been seen

Writes a fixed-format block at the END of STATE.md (preserves chronological log).

No env vars required — pure repo introspection.
"""
from __future__ import annotations
import csv
import datetime as dt
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
STATE = ROOT / "STATE.md"
OUTBOUND = ROOT / "outbound"
QUEUE = ROOT / "intake-queue"


def _csv_rows(path: Path) -> list[dict]:
    if not path.exists():
        return []
    with path.open() as f:
        return list(csv.DictReader(f))


def _within(ts_str: str, since: dt.datetime) -> bool:
    if not ts_str:
        return False
    try:
        t = dt.datetime.fromisoformat(ts_str.replace("Z", "+00:00")).replace(tzinfo=None)
        return t >= since
    except Exception:
        return False


def _count_files_since(folder: Path, since: dt.datetime, pattern: str = "*.json") -> int:
    if not folder.exists():
        return 0
    n = 0
    for p in folder.glob(pattern):
        if dt.datetime.utcfromtimestamp(p.stat().st_mtime) >= since:
            n += 1
    return n


def build_block() -> str:
    now = dt.datetime.now(dt.timezone.utc).replace(tzinfo=None)
    since = now - dt.timedelta(days=7)
    week_str = now.strftime("%Y-W%V")
    date_str = now.strftime("%Y-%m-%d")

    sent = _csv_rows(OUTBOUND / "sent.csv")
    sent_week = [r for r in sent if _within(r.get("ts", ""), since)]
    sent_ok_week = [r for r in sent_week if r.get("ok") in ("True", "true", "1", True)]

    signups = _csv_rows(OUTBOUND / "signups.csv")
    signups_week = [r for r in signups if _within(r.get("ts", ""), since)]
    onboarded_ok_week = [r for r in signups_week if r.get("onboarding_sent") in ("True", "true", "1", True)]

    intakes = _csv_rows(OUTBOUND / "intakes.csv")
    intakes_week = [r for r in intakes if _within(r.get("ts", ""), since)]

    processed_week = _count_files_since(QUEUE / "_processed", since, "*.result.json")
    failed_week = _count_files_since(QUEUE / "_failed", since, "*.error.txt")

    cold_replies = _csv_rows(OUTBOUND / "cold_replies.csv")
    cold_replies_week = [r for r in cold_replies if _within(r.get("ts", ""), since)]

    needs_human = _csv_rows(OUTBOUND / "needs_human.csv")
    needs_human_open = [r for r in needs_human if _within(r.get("ts", ""), since)]

    pending_in_queue = sum(1 for _ in QUEUE.glob("*.json") if _.is_file())

    lines = [
        f"## {date_str} — WEEKLY STATUS — {week_str}",
        "",
        f"_Auto-generated by `weekly-status.yml` over the prior 7 days._",
        "",
        "### Acquisition",
        f"- Cold emails sent: **{len(sent_week)}** (delivered ok: {len(sent_ok_week)})",
        f"- Pilot signups received: **{len(signups_week)}** (onboarded ok: {len(onboarded_ok_week)})",
        f"- Cold replies received: **{len(cold_replies_week)}**",
        "",
        "### Pipeline",
        f"- Intakes queued this week: **{len(intakes_week)}**",
        f"- Intakes processed: **{processed_week}**",
        f"- Intakes failed: **{failed_week}**",
        f"- Currently pending in queue: **{pending_in_queue}**",
        "",
        "### Operator attention",
        f"- Items in `outbound/needs_human.csv` this week: **{len(needs_human_open)}**",
    ]
    if needs_human_open:
        lines.append("")
        lines.append("Preview of items needing human review:")
        for r in needs_human_open[:5]:
            preview = (r.get("preview") or "").replace("\n", " ")[:160]
            lines.append(f"  - from `{r.get('from','')[:50]}` — `{r.get('subject','')[:60]}` — {preview}")

    lines += [
        "",
        "### Workflow health",
        "_Check the Actions tab for red runs in the last 7 days: https://github.com/finleystephenson/crewOS/actions_",
        "",
    ]
    return "\n".join(lines)


def append_to_state() -> dict:
    """Insert the weekly block at the top of the chronological log (just below
    the file header marker `_Updated end-of-session. Most recent at top._`).
    Falls back to prepending after the first H1 if the marker isn't present.
    """
    block = build_block()
    state_text = STATE.read_text() if STATE.exists() else "# STATE\n\n_Updated end-of-session. Most recent at top._\n\n"

    marker = "_Updated end-of-session. Most recent at top._"
    if marker in state_text:
        head, _, tail = state_text.partition(marker)
        new_text = head + marker + "\n\n" + block + "\n" + tail.lstrip("\n")
    else:
        # Fallback: insert after the first `# ` heading line, if any.
        lines = state_text.splitlines(keepends=True)
        insert_at = 1
        for i, ln in enumerate(lines):
            if ln.startswith("# "):
                insert_at = i + 1
                break
        new_text = "".join(lines[:insert_at]) + "\n" + block + "\n" + "".join(lines[insert_at:])

    STATE.write_text(new_text)
    return {"inserted_at_top": True, "bytes": len(block)}


def _main() -> int:
    result = append_to_state()
    print(json.dumps(result, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(_main())
